---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: <docker-hub-namespace>/<docker-hub-img>:<tag>
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: 3000
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: PGHOST
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: PGPASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: PGDATABASE
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: PGPORT
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: AUTH_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: GOOGLE_CALLBACK_URL
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: GOOGLE_CLIENT_SECRET
