import type { NextPage } from "next";
import Head from "next/head";
import { publicClient, gql } from "../graphql";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const resp = await publicClient.query({
    query: gql`
      query GoogleAuthUrl {
        googleAuthUrl
      }
    `,
  });

  return {
    props: {
      googleAuthUrl: resp?.data?.googleAuthUrl,
    },
  };
}

const Home: NextPage<{ googleAuthUrl: string }> = ({ googleAuthUrl }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href={googleAuthUrl}>Log into Google</a>
        </h1>
      </main>
    </div>
  );
};

export default Home;
